; PlatformIO Project Configuration File
; 风筝俯仰角控制器 - LGT8F328P (Arduino Nano Compatible)

[platformio]
default_envs = lgt8f328p
description = This is customized serial servo

[env:LGT8F328P]
platform = lgt8f
board = LGT8F328P
framework = arduino
lib_deps = 
	arduino-libraries/Servo @ ^1.3.0
